### ISSUE TITLE
Consider moving the `conditional-type-checks` to `devDependencies`

### ISSUE THREAD

**Issue by ttphi88** [GabrielCTroia/ts-async-results#1]
Hi, I've just found this package and it's amazing 👍 

Just one suggestion, we should move the packages (only `conditional-type-checks` for now) only used in the test to the `devDependencies` so that the users don't have to download them.

What do you think?

**Comment by GabrielCTroia** [comment]
I agree! Thanks for the suggestion and the kind words!

I don't have much bandwidth at the moment, but if you open a PR I'm happy to merge it!

**Comment by GabrielCTroia** [comment]
Solved this in the current version! Thanks for mentioning it! Going to close!
